opts:
  backend:
    kube:
      verbose_events: 1   # to get events printed
      dir: /mnt/data/stimela-test
      namespace: rarg-test-compute
      volumes:
        rarg-test-compute-pvc: /mnt/data

      ## override user/group ID
      uid: 1669
      gid: 1669
      ## you can specify a global memory default for pods here,
      ## otherwise go on a per-cab or per-step basis
      # memory: 64Gi

      ## some predefined pod specs
      predefined_pod_specs:
        admin:
          nodeSelector:
            rarg/node-class: admin
        thin:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.large
            rarg/capacity-type: SPOT
        fat:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m6i.4xlarge
            rarg/capacity-type: ON_DEMAND

      ## default type to use
      job_pod:
        type: admin 
      
      env:
        NUMBA_CACHE_DIR: /mnt/data/stimela-test

    # # we have this set up a a pull-through cache for the standard registry
    # override_registries:
    #   quay.io/stimela2: 800133935729.dkr.ecr.af-south-1.amazonaws.com/quay/stimela2
