opts:
  backend:
    kube:
      verbose_events: 1   # to get events printed
      dir: /mnt/data/stimela-test
      namespace: rarg-test-compute
      volumes:
        rarg-test-compute-efs-pvc: /mnt/data

      ## override user/group ID
      uid: 0
      gid: 0
      ## you can specify a global memory default for pods here,
      ## otherwise go on a per-cab or per-step basis
      # memory: 64Gi

      ## some predefined pod specs
      predefined_pod_specs:
        admin:
          nodeSelector:
            rarg/node-class: admin
        thin:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.large
            rarg/capacity-type: ON_DEMAND
        medium:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.4xlarge
            rarg/capacity-type: ON_DEMAND
        fat:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: r5.16xlarge

      ## default type to use
      job_pod:
        type: admin

      env:
        NUMBA_CACHE_DIR: /mnt/data/stimela-test
        CONFIGURATT_CACHE_DIR: /mnt/data/stimela-test
