opts:
  backend:
    kube:
      enable: true
      dir: /mnt/data/pfb-test
      namespace: rarg-test-compute
      volumes:
        rarg-test-compute-efs-pvc:
          mount: /mnt/data

      ## override user/group ID
      user:
        uid: 1000
        gid: 1000
      ## you can specify a global memory default for pods here,
      ## otherwise go on a per-cab or per-step basis
      # memory: 64Gi

      ## some predefined pod specs
      predefined_pod_specs:
        admin:
          nodeSelector:
            rarg/node-class: admin
        scheduler:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m6i.large
            rarg/capacity-type: ON_DEMAND
        tiny:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: m5.large
            rarg/capacity-type: ON_DEMAND
        thin:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: c6in.2xlarge
            rarg/capacity-type: ON_DEMAND
        pudgy:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: c6in.8xlarge
            rarg/capacity-type: ON_DEMAND
        fat:
          nodeSelector:
            rarg/node-class: compute
            rarg/instance-type: c6in.24xlarge
            rarg/capacity-type: ON_DEMAND


      ## default type to use
      job_pod:
        type: admin

      env:
        NUMBA_CACHE_DIR: /mnt/data/pfb-test
        CONFIGURATT_CACHE_DIR: /mnt/data/pfb-test
