#
# USAGE:
# 1. Add your public keys to the authorized_keys entry in the ConfigMap below
# 2. $ kubectl apply -f ssh-server.yaml
# 3. $ kubectl -n rarg-test-compute port-forward ssh-server 2222:22
# 4. $ ssh -p 2222 root@localhost
# 5. $ kubectl delete -f ssh-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: rarg-test-compute
data:
  # Insert your public keys here. For example.
  # $ cat ~/.ssh/id_rsa.pub
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaZn93eTXEo7m4a4djLWWrs+AggphSHu7R/87XUa40hGC0UBdjxM+wOeTeEAFAh9rQR9/Ioq4cRlqDAgf2Gt/XsMa1shtYNyYHHIJh7ml7AGc+IolQASrCMNWI3t4ZJT15bydge424y5aNpT3PPqvQUFdBcfj+PcCaBc9OQJ3eHbpMBd8QaA9XmAXforNMoVWW9K5pSH7rJcsu9KlP1XKwDOHR4ihhYUjyqF2oWWi5HnrQmDwWelkyxLPxH/GsIKnF+aYHl7nOq3n6hTXf/Dy2lhMXfGgd64X5wussKM+vZ1xbaOX+wqIGiFF2fy5YIgvP9sTvQiQInoiEqNser0mf landman@LAPTOP-ED4N50Q2
---
apiVersion: v1
kind: Pod
metadata:
  name: ssh-server
  namespace: rarg-test-compute
  labels:
    app: ssh-server
spec:
  restartPolicy: Always
  automountServiceAccountToken: true
  serviceAccountName: compute-runner
  nodeSelector:
    rarg/node-class: compute
    rarg/instance-type: m5.large
    rarg/capacity-type: ON_DEMAND
  containers:
  - name: ssh-server
    image: jskenyon/ssh-server:latest
    # image: quay.io/stimela2/pfb-imaging:cc0.1.3
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 22
    volumeMounts:
    - mountPath: /root/.ssh/authorized_keys
      subPath: authorized_keys
      name: ssh-volume
  # Mounts the ConfigMap
  volumes:
  - name: ssh-volume
    configMap:
      name: ssh-config
      defaultMode: 384  # 0600 octal
# Faster to just kubectl port-forward
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ssh-service
#   namespace: rarg-test-compute
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 22222
#     targetPort: 22
#   selector:
#     app: application
